CREATE TABLE users (
                       user_id VARCHAR2(50) primary KEY NOT NULL,
                       role NUMBER DEFAULT 0	NOT NULL,
                       user_pw varchar2(50) NOT NULL,
                       name varchar2(20) NOT NULL,
                       serial_num_f varchar2(7) NOT NULL,
                       serial_num_l varchar2(100) NOT NULL,
                       phone varchar2(15) NOT NULL,
                       height NUMBER NOT NULL,
                       weight NUMBER NOT NULL,
                       join_at timestamp DEFAULT SYSDATE NOT NULL,
                       alarm_agree varchar2(10) NOT NULL,
                       profileImg varchar2(2000) NOT NULL,
                       point NUMBER DEFAULT 1 NOT NULL
);

SELECT * FROM users;

CREATE TABLE Food_Category (
                               id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                               food_name 	varchar2(255) NOT NULL,
                               kcal NUMBER NOT NULL
);

CREATE TABLE Food_Like (
                           id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                           food_id NUMBER NOT NULL,
                           liked_at timestamp	DEFAULT SYSDATE	NOT NULL
);


CREATE TABLE Meal (
                      meal_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                      meal_date DATE NOT NULL,
                      meal_time time NOT NULL
);


CREATE TABLE Meal_detail  (
                              id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                              meal_id NUMBER NOT NULL,
                              food_id NUMBER NOT NULL,
                              meal varchar2(50) NOT NULL,
                              amount float NOT NULL
);

CREATE TABLE  Sport_Category  (
                                  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                  sport_name varchar2(255) NOT NULL,
                                  kcal float NOT NULL
);


SELECT *FROM sport_category;

CREATE TABLE Sport_Like  (
                             id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                             sport_category_id NUMBER NOT NULL,
                             liked_at timestamp	DEFAULT SYSDATE	NOT NULL
);


CREATE TABLE Sport_Routine  (
                                id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                user_id VARCHAR(50) NOT NULL,
                                sport_routine_name varchar(255) NOT NULL
);

CREATE TABLE  Sport_Routine_List  (
                                      id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                      sport_routine_id NUMBER NOT NULL,
                                      sport_category_id NUMBER NOT NULL,
                                      set_count NUMBER NOT NULL,
                                      sport_count NUMBER NOT NULL,
                                      volume NUMBER NOT NULL,
                                      routine_start timestamp,
                                      routine_end timestamp
);

CREATE TABLE Weight_Record  (
                                id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                user_id VARCHAR2(50) NOT NULL,
                                weight_now NUMBER NOT NULL,
                                record_at timestamp DEFAULT SYSDATE NOT NULL
);

CREATE TABLE Alert (
                       id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                       type_id number NOT NULL,
                       user_id VARCHAR2(50) NOT NULL,
                       read_or_not varchar2(10) NOT NULL,
                       created_at timestamp DEFAULT SYSDATE NOT NULL
);

CREATE TABLE Alert_type  (
                             type_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                             message varchar2(255) NOT NULL,
                             altype varchar(20) NOT NULL
);
